name: Publish to NuGet

on:
  workflow_dispatch:
  push:
    branches: [ "master", "main" ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore ./src/SenDev.Xaf.OneTimeMethods.slnx

    - name: Build
      run: dotnet build ./src/SenDev.Xaf.OneTimeMethods.slnx --configuration Release --no-restore

    - name: Test
      run: dotnet test ./src/SenDev.Xaf.OneTimeMethods.Tests/SenDev.Xaf.OneTimeMethods.Tests.csproj --configuration Release --no-build --no-restore

    - name: Pack
      run: dotnet pack ./src/SenDev.Xaf.OneTimeMethods.slnx --configuration Release --no-build --no-restore --output ./artifacts

    - name: Publish to NuGet
      run: dotnet nuget push "./artifacts/SenDev.Xaf.OneTimeMethods.Xpo.*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
